[[dev-stream-apps]]
= Developing Stream applications

--
In this section we will cover how to create, test and run Spring Cloud Stream applications locally and on Cloud Foundry.  We will also show how to map these applications into Spring Cloud Data Flow and deploy them locally and on Cloud Foundry.
--

[[running-existing-apps]]
== Running existing applications

run cmd line equivalent of http | log

== Creating and testing a custom processor application

create, uppercase and unit test it.

run cmd line equivalent of http | uppercase | log

== Mapping the application to Spring Cloud Data Flow

register apps, create stream and deploy it locally

== Integration testing locally

use the new integration testing library locally

== Integration testing on Cloud Foundry

== Deploying on Cloud Foundry

[[dev-customizing-stream-apps]]
= Customizing Stream applications

== Changing the messaging middleware

== Changing the serialization

== Changing the number of instances

no partitioning, basic scale up.

== Composing applications


[[dev-multiple-streamstopologies]]
= Collaborating streams

Show More complex topologies

== real-time analytics

== Fan in/Fan out

[[dev-data-partitioning]]
= Data Partitioning


